package de.drazil.homeautomation.smartdevices;

public enum HmAttributes {

    RSSI_DEVICE("RSSI_DEVICE"), CURRENT("CURRENT"), FREQUENCY("FREQUENCY"), VOLTAGE("VOLTAGE"), POWER("POWER"),
    STATE("STATE"), LOWBAT("LOWBAT"), UNREACH("UNREACH"), VALVE_ERROR_POSITION("VALVE_ERROR_POSITION"),
    TEMPERATURE("TEMPERATURE"), SET_TEMPERATURE("SET_TEMPERATURE"), ACTUAL_TEMPERATURE("ACTUAL_TEMPERATURE"),
    HUMIDITY("HUMIDITY"), VALVE_STATE("VALVE_STATE"), ERROR("ERROR"), SHOW_HUMIDITY("SHOW_HUMIDITY"),
    BUTTON_RESPONSE_WITHOUT_BACKLIGHT("BUTTON_RESPONSE_WITHOUT_BACKLIGHT"), BACKLIGHT_ON_TIME("BACKLIGHT_ON_TIME"),
    CHANNEL0("CHANNEL0"), CHANNEL1("CHANNEL2"), CHANNEL2("CHANNEL3"), WINDOW_STATE("WINDOW_STATE"),
    ERROR_SMOKE_CHAMBER("ERROR_SMOKE_CHAMBER"), ERROR_ALARM_TEST("ERROR_ALARM_TEST"), INSTALL_TEST("INSTALL_TEST"),
    BATTERY_STATE("BATTERY_STATE"), CONTROL_MODE("CONTROL_MODE"), AUTO_MODE("AUTO_MODE"), MANU_MODE("MANU_MODE"),
    BOOST_MODE("BOOST_MODE"), WEEK_PROGRAM_POINTER("WEEK_PROGRAM_POINTER"), GLOBAL_BUTTON_LOCK("GLOBAL_BUTTON_LOCK"),
    BUTTON_LOCK("BUTTON_LOCK"), BURST_RX("BURST_RX"), PREFIX_P1("PREFIX_P1"), PREFIX_P2("PREFIX_P2"),
    PREFIX_P3("PREFIX_P3"), STARTTIME_PART("STARTTIME_"), ENDTIME_PART("ENDTIME_"), TEMPERATURE_PART("TEMPERATURE_");

    private final String name;

    HmAttributes(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        return getName();
    }
}